# Generated by Django 5.2.1 on 2025-05-27 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('Course', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('College', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('SubjCode', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('SubjDescription', models.CharField(max_length=45)),
                ('Units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('StudentID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=45)),
                ('Course', models.ForeignKey(db_column='Course', on_delete=django.db.models.deletion.CASCADE, to='dashboard.coursetable')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('Contactid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('ContactNumber', models.CharField(max_length=45)),
                ('StudentID', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='dashboard.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='dashboard.studenttable')),
                ('SubjCode', models.ForeignKey(db_column='SubjCode', on_delete=django.db.models.deletion.CASCADE, to='dashboard.subjecttable')),
            ],
            options={
                'unique_together': {('StudentID', 'SubjCode')},
            },
        ),
    ]
